name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Sync to HF
        uses: huggingface/hub-sync@v1.0
        with:
          github_repo_id: SeamusGerner/dsc465-final-project
          huggingface_repo_id: username/repo-name
          repo_type: space # or 'model' or 'dataset'
          hf_token: ${{ secrets.HF_TOKEN }}
